spring.application.name=estudio

server.error.whitelabel.enabled=false


# ---- Esto externaliza los nombres -> Conexión con ConfiguracionSeguridad ----
el.nombre=usuario
la.clave=clave


# ---- Estas tres hacen que /actuator/health devuelva información detallada: memoria, disco, conexiones, etc. ----
management.endpoints.web.exposure.include=*
management.endpoint.health.show-components=always
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true



# ---- Añadir esto cuando quieras usar persistencia ----
spring.datasource.url=jdbc:h2:file:./dbdata
spring.datasource.username=sa
spring.h2.console.enabled=true
spring.jpa.generate-ddl=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.jpa.defer-datasource-initialization=true


